# Generated by Django 6.0.4 on 2026-04-09 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Chuyến du lịch', 'verbose_name_plural': 'Các chuyến du lịch'},
        ),
        migrations.AlterField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slots',
            field=models.IntegerField(verbose_name='Số chỗ'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tên Tour'),
        ),
    ]
