# Generated by Django 6.0.4 on 2026-04-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_options_alter_tour_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='address',
            field=models.CharField(default='Việt Nam', max_length=255),
        ),
    ]
